### DISCUSSION TITLE
Laravel 7, Sanctum and Docker Issues

### DISCUSSION THREAD

**Discussion by shpeedle** [laravel/framework#35230] [Q&A]
I've been stuck for days now trying to get Laravel7 and Sanctum to work with docker and nginx.

It seems no matter what I try I get 401 unauthorized when I try an API route with a Vue SPA that contains an authenticated session cookie and csrf token.

I followed [this](https://laracasts.com/series/whats-new-in-laravel-7/episodes/6) tutorial except I'm using docker and nginx.

I'm starting to think that the problem has something to do with docker/nginx or maybe the version combination with Laravel7 and Sanctum libraries.

Any suggestions are greatly appreciated.

Here are some of my files:

### Dockerfile.dev
```
FROM php:7.4.0-fpm

# Arguments defined in docker-compose.yml
ARG user
ARG uid

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    gnupg2 \
    libzip-dev \
    nano \
    wget

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd zip

# Install XDebugLike
RUN yes | pecl install xdebug \
    && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_enable=on" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_connect_back=0" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_port=9090" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_host=host.docker.internal" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.var_display_max_depth=5" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.var_display_max_children=256" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.var_display_max_data = 1024" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_log=/var/www/xdebug.log" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.idekey=VSCODE" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_autostart=on" >> /usr/local/etc/php/conf.d/xdebug.ini

# Use the default development configuration
# RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Create system user to run Composer and Artisan Commands
RUN useradd -G www-data,root -u $uid -d /home/$user $user
RUN mkdir -p /home/$user/.composer && \
    chown -R $user:$user /home/$user

# replace shell with bash so we can source files
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

# update the repository sources list
# and install dependencies
RUN apt-get update \
    && apt-get install -y curl \
    && apt-get -y autoclean

# Set working directory
WORKDIR /var/www

RUN chown -R $user:$user /var/www

COPY --chown=$user:$user . .

# xdebug
EXPOSE 9090

USER $user

```

### docker-compose.yml
```
version: "3.7"
services:
  # ######################################
  # MYSQL
  #
  # ######################################
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
  # ######################################
  # PHP ADMIN
  #
  # ######################################
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
  # ######################################
  # LARAVEL APP
  #
  # ######################################
  app:
    restart: unless-stopped
    depends_on:
      - db
  # ######################################
  # NGINX
  #
  # ######################################
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - app

```

### docker-compose.override.yml
```
version: "3.7"
services:
  # ######################################
  # MYSQL
  #
  # ######################################
  db:
    container_name: laravel_vue_sanctum-db
    restart: unless-stopped
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql_dev
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - laravel_vue_sanctum
  # ######################################
  # PHP ADMIN
  #
  # ######################################
  phpmyadmin:
    ports:
      - "8081:80"
    networks:
      - laravel_vue_sanctum
  # ######################################
  # LARAVEL APP
  #
  # ######################################
  app:
    build:
      args:
        user: devuser
        uid: 1000
      context: ./
      dockerfile: Dockerfile.dev
    environment:
      DB_HOST: laravel_vue_sanctum-db
    image: laravel_vue_sanctum_app
    container_name: laravel_vue_sanctum-app
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laravel_vue_sanctum
  # ######################################
  # NGINX
  #
  # ######################################
  nginx:
    container_name: laravel_vue_sanctum-nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/dev:/etc/nginx/conf.d
    networks:
      - laravel_vue_sanctum
    depends_on:
      - app
# ######################################
# NETWORKS
#
# ######################################
networks:
  laravel_vue_sanctum:

```

### nginx config
```
server {
    listen 80;
    index index.php index.html;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    root /var/www/public;

    # general laravel php
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # laravel routes php
    location / {
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
    }
}

```

### composer.json
```
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.2.5|^8.0",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^6.3.1|^7.0.1",
        "laravel/framework": "^7.29",
        "laravel/sanctum": "^2.8",
        "laravel/tinker": "^2.5",
        "laravel/ui": "2.x"
    },
    "require-dev": {
        "facade/ignition": "^2.0",
        "fakerphp/faker": "^1.9.1",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^4.3",
        "phpunit/phpunit": "^8.5.8|^9.3.3"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}

```
