### DISCUSSION TITLE
Laravel Dusk in Docker: Selenium can't start Chrome

### DISCUSSION THREAD

**Discussion by osmianski** [laravel/framework#46958] [Q&A]
- Laravel v10.9.0
- PHP v8.2.3
- laravel/dusk v7.7.1
- orchestra/testbench v8.5.1
- orchestra/testbench-dusk v8.6.0
- orchestra/dusk-updater v2.0.1
- pestphp/pest v2.6.0

## Description

I'm developing a package with an accompanying example application (in the `/example-app` directory) in a non-Sail Docker environment.

Now, I want to add browser tests that work with the example application - and I can't make Laravel Dusk to work. It seems that the test connects to Selenium successfully, but Selenium for some reason can't start Chrome, or can't establish connection with it.

Any ideas are welcome.

## Console output

```bash
$ bin/pest --stop-on-error

   FAIL  Tests\Browser\ExampleTest
  ⨯ it starts a browser                                                                              1.01s  
  ────────────────────────────────────────────────────────────────────────────────────────────────────────  
   FAILED  Tests\Browser\ExampleTest > it starts a browser                     SessionNotCreatedException   
  Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Handshake response does not match any supported protocol 
Host info: host: '669ff3f704ee', ip: '172.27.0.4'
Build info: version: '4.9.0', revision: 'd7057100a6'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.14.0-1048-oem', java.version: '11.0.18'
Driver info: driver.version: unknown
Build info: version: '4.9.0', revision: 'd7057100a6'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.14.0-1048-oem', java.version: '11.0.18'
Driver info: driver.version: unknown

  at vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php:130
    126▕                     throw new NoSuchShadowRootException($message, $results);
    127▕                 case 'script timeout':
    128▕                     throw new ScriptTimeoutException($message, $results);
    129▕                 case 'session not created':
  ➜ 130▕                     throw new SessionNotCreatedException($message, $results);
    131▕                 case 'stale element reference':
    132▕                     throw new StaleElementReferenceException($message, $results);
    133▕                 case 'detached shadow root':
    134▕                     throw new DetachedShadowRootException($message, $results);

      +4 vendor frames 
  5   tests/BrowserTestCase.php:39
      +1 vendor frames 
  7   tests/Browser/ExampleTest.php:4


  Tests:    1 failed, 17 pending (0 assertions)
  Duration: 1.09s
```

Output from Selenium console:

```
2023-05-04T10:17:45.545680891Z 10:17:45.545 INFO [LocalDistributor.newSession] - Session request received by the Distributor: 
2023-05-04T10:17:45.545716843Z  [Capabilities {browserName: chrome, goog:chromeOptions: {args: [--disable-gpu, --headless=new, --ignore-certificate-errors, --ignore-certificate-errors..., --verbose, --whitelisted-ips, --disable-dev-shm-usage], w3c: false}}]
2023-05-04T10:17:45.550145034Z Starting ChromeDriver 112.0.5615.49 (bd2a7bcb881c11e8cfe3078709382934e3916914-refs/branch-heads/5615@{#936}) on port 24481
2023-05-04T10:17:45.550179137Z Only local connections are allowed.
2023-05-04T10:17:45.550183652Z Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
2023-05-04T10:17:45.551177396Z ChromeDriver was started successfully.
2023-05-04T10:17:45.551233471Z [1683195465.551][SEVERE]: bind() failed: Cannot assign requested address (99)
2023-05-04T10:17:45.604519288Z 10:17:45.604 WARN [DriverServiceSessionFactory.apply] - Error while creating session with the driver service. Stopping driver service: Could not start a new session. Handshake response does not match any supported protocol 
2023-05-04T10:17:45.604550164Z Host info: host: '669ff3f704ee', ip: '172.27.0.4'
2023-05-04T10:17:45.604553991Z Build info: version: '4.9.0', revision: 'd7057100a6'
2023-05-04T10:17:45.604557229Z System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.14.0-1048-oem', java.version: '11.0.18'
2023-05-04T10:17:45.604560474Z Driver info: driver.version: unknown
2023-05-04T10:17:45.649115670Z 
```

## Pest test

The test, `tests/Browser/ExampleTest.php`:

```php
it('starts a browser', function () {
    $this->browse(function ($browser) {
        $browser->visit('/')->assertSee('Laravel');
    });
});
```

The base class for browser tests, `tests/BrowserTestCase.php`:

```php
use Facebook\WebDriver\Remote\RemoteWebDriver;
use Orchestra\Testbench\Dusk\Options as DuskOptions;
use Orchestra\Testbench\Dusk\TestCase as BaseTestCase;

class BrowserTestCase extends BaseTestCase
{
    public static function prepare(): void
    {
        // This method is empty on purpose. In the parent class, it starts
        // the local headless Chrome to be used with the local Selenium.
        //
        // However, our Selenium runs in a separate container, and the
        // headless Chrome runs there, too.
        //
        // So, we don't need to start the local headless Chrome.
    }

    protected function driver(): RemoteWebDriver
    {
        DuskOptions::withoutUI();

        // this is my experiments with Chrome start parameters, none of them made things better
        DuskOptions::ignoreSslErrors();
        DuskOptions::addArgument('--ignore-certificate-errors-spki-list');
        DuskOptions::addArgument('--verbose');
        DuskOptions::addArgument('--whitelisted-ips');
        DuskOptions::addArgument('--disable-dev-shm-usage');

        return parent::driver();
    }
}
```

## Docker setup

`docker-compose.yml`:

```yaml
version: "2.4"

services:
  webserver:
    image: nginx:alpine
    container_name: foundation
    working_dir: /
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.foundation.rule=Host(`foundation.localhost`)"
      - "traefik.http.routers.foundation.entrypoints=web"
      - "traefik.docker.network=wa_net"
    restart: always
    networks:
      - default
      - wa_net

  php-fpm:
    image: our/php:8.2.3-xdebug
    container_name: foundation-fpm
    user: $UID:$GID
    volumes:
      - ./:/var/www
      - ./docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/custom.ini
    restart: always
    labels:
      - "traefik.enable=false"
    networks:
      - default
      - wa_net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  selenium:
    image: 'selenium/standalone-chrome'
    shm_size: 2gb
    volumes:
      - '/dev/shm:/dev/shm'
    networks:
      - default
      - wa_net
```
