### ISSUE TITLE
Sessions don't work in cloned quickstart app

### ISSUE THREAD

**Issue by jimlei** [laravel/framework#10999]
After vagrant up the site loads fine. But registering/logging in throws a "TokenMismatchException in VerifyCsrfToken.php line 53"

It seems to create a new session for each page load. I've tried both the default file and the database driver

```
php artisan session:table
composer dump-autoload
php artisan migrate
```

---

Followed instructions to set up Homestead http://laravel.com/docs/5.1/homestead

```
vagrant box add laravel/homestead
git clone https://github.com/laravel/homestead.git Homestead
bash init.sh
```

~/.homestead/Homestead.yaml
```
---
ip: "192.168.10.10"
memory: 8192
cpus: 3
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Code
      to: /home/vagrant/Code
      type: nfs

sites:
    - map: quickstart.app
      to: /home/vagrant/Code/quickstart/public

databases:
    - homestead

variables:
    - key: 'APP_ENV'
      value: 'local'
    - key: 'APP_DEBUG'
      value: 'true'
```

Then I cloned the quick start project

```
git clone https://github.com/laravel/quickstart-intermediate quickstart
cd quickstart
composer install
php artisan migrate
```
