### ISSUE TITLE
Nested subdomain vapor deployments

### ISSUE THREAD

**Issue by samstreet** [laravel/framework#31958]
Given the following vapor.yml file:

```
id: XXXX
name: foo
environments:
  production:
    memory: 1024
    cli-memory: 512
    domain: service.name.domain.co.uk
    build:
      - 'composer install --no-dev --classmap-authoritative'
  staging:
    memory: 1024
    cli-memory: 512
    domain: stagingservice.name.domain.co.uk
    build:
      - 'composer install --classmap-authoritative'
```
I want to be able to deploy to whatever domain combination that I need to, but keep getting hit with:

```
Whoops! There were some problems with your request.

    - [service.name.domain.co.uk] Please do not specify more than one subdomain.
```

What is the best way for me to go about having domains like this, or even going as far as fixing it?
