### ISSUE TITLE
Scheduler don't uses env-variable handed over via docker-compose

### ISSUE THREAD

**Issue by Orscheler** [laravel/framework#46956]
### Laravel Version

10.4.1

### PHP Version

8.2.4

### Database Driver & Version

10.10.2-MariaDB

### Description

We have the following setup:

docker-compose containing the environment variable for the affected container:
```
environment:
            APP_ENV: int
```

The `.env` inside the Laravel root directory doesn't include the `APP_ENV `variable.

The `config/app.php` is being configured, to use "production" in case the APP_ENV variable is not being configured.
```
'env' => env(
   'APP_ENV', 
   'production'
),
```

In `app/Console/Kernel.php` several jobs are being defined, which also make use of the environment variable.
We also added `Log::info('Environment: '.config('app.env'));` to the schedule.

Furthermore there is a cronjob being defined, that triggers the scheduler:
`* * * * * /usr/local/bin/php /app/artisan schedule:run >> /var/log/cron.log 2>&1`

The cronjob is running with the root-user, however the given env-variable is not being used, but the default instead:
```
[2023-05-04 09:40:01] production.INFO: Environment: production  
[2023-05-04 09:41:01] production.INFO: Environment: production  
[2023-05-04 09:42:02] production.INFO: Environment: production  
[2023-05-04 09:43:01] production.INFO: Environment: production 
``` 

Even the variable is being set:
```
root@2a57ec5602df:/app# export | grep APP_ENV
declare -x APP_ENV="int"
```

When running the scheduler manually (also with the user root)  `/usr/local/bin/php /app/artisan schedule:run`, everything is being fine
```
[2023-05-04 09:38:38] int.INFO: Environment: int
[2023-05-04 09:38:44] int.INFO: Environment: int
```

### Steps To Reproduce

See example above

**Comment by andumy** [comment]
Hey @Orscheler 
I've tried to replicate your issue, but It seems that I cannot reproduce the bug. How does your docker-compose file look like?

The setup I've used to replicate:
- Set the `APP_ENV` as an environment in the php container;
- remove the `APP_ENV` from .env file;
- check that `'env' => env('APP_ENV', 'production'),` exists in `config/app.php`;
- use the bellow setup

`docker-compose.yml`:
```
version: '2.4'

services:
    php:
        image: php:8.2-fpm
        environment:
            APP_ENV: int
        volumes:
            - .:/var/www/html
        networks:
            - test

    nginx:
        image: nginx:latest
        volumes:
            - .:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8080:80
        networks:
            - test

networks:
    test:
```

`default.conf`:
```
server {
    listen 80;
    root /var/www/html/public;

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ ^/index\.php(/|$) {
        fastcgi_pass php:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;

        fastcgi_buffer_size 128k;
        fastcgi_buffers 4 256k;
        fastcgi_busy_buffers_size 256k;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTPS off;

         proxy_set_header Host $host;
         proxy_set_header X-Forwarded-Host $host;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-Server $host;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    error_log /var/log/nginx/laravel_error.log;
    access_log /var/log/nginx/laravel_access.log;
}
```

`routes/web.php`:
```
Route::get('/', function () {
    dd(config('app.env'));
});
```

**Comment by nunomaduro** [comment]
@Orscheler, have you managed to resolve the issue yet? If not, you could attempt to set the environment variable at the `service > php` level as instructed by @andumy:

```

services:
    php:
        image: php:8.2-fpm
        environment:
            APP_ENV: int
```

In case this solution doesn't work, would you be willing to create an open-source repository with a new Laravel application, the necessary changes to reproduce the issue, and your Dockerfile? This will help us to attempt reproducing the issue on our local environment. No worries, if we are able to verify that there is an issue here, I will re-open this issue.
