### ISSUE TITLE
[Bug] APP_NAME must be defined in .env, if it is defined in the compose file it horizon is inactive

### ISSUE THREAD

**Issue by peaklabs-dev** [laravel/framework#52624]
### Laravel Version

11.15.0

### PHP Version

8.2.22

### Database Driver & Version

"pgsql" and version "PostgreSQL 15.8 on aarch64-unknown-linux-musl, compiled by gcc (Alpine 13.2.1_git20240309) 13.2.1 20240309, 64-bit"

### Description

I am working on Coolify, I made some changes to the `compose files` and the `.env files` and found out when the `APP_NAME` is defined in the `compose file` and not in the `.env file` the horizon scheduler is inactive.

### Steps To Reproduce

1. https://github.com/coollabsio/coolify fork the repo (If there is more help required use this guide: https://github.com/coollabsio/coolify/blob/main/CONTRIBUTING.md)
2. Add `APP_NAME` in the `docker-compose.dev.yml` (note this also happens when adding the line like this `APP_NAME: "${APP_NAME:-Coolify}"`):
```env
APP_NAME: "Coolify Development"
```
3. Copy `.env.development.example` to `.env` and remove `APP_NAME="Coolify Development"` form `.env`
4. Install spin up if you have not already https://serversideup.net/open-source/spin/docs/installation/install-macos
5. run `spin up`
6. check you Laravel scheduler here: http://localhost:8000/horizon/dashboard
7. It will say inactive
<img width="1497" alt="image" src="https://github.com/user-attachments/assets/a443eccf-2e4b-400e-98f2-48a9dcd8dc73">

8. Add the `APP_NAME="Coolify Development"` in the .env file and remove the `APP_NAME` line in the `docker-compose.dev.yml` and then ctrl + c and then run `spin up` again
9. Now Horizon works
<img width="1562" alt="image" src="https://github.com/user-attachments/assets/d4c70541-14df-4451-ab7a-95ced276ebe2">

**This behavior should not happen.**
Full `docker-compose.dev.yml` for reference:
```yaml
services:
  coolify:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - "${APP_PORT:-8000}:80"
    environment:
      APP_NAME: "Coolify Development"
      PUID: "${USERID:-1000}"
      PGID: "${GROUPID:-1000}"
      SSL_MODE: "off"
      AUTORUN_LARAVEL_STORAGE_LINK: "false"
      AUTORUN_LARAVEL_MIGRATION: "false"
      PUSHER_HOST: "${PUSHER_HOST}"
      PUSHER_PORT: "${PUSHER_PORT}"
      PUSHER_SCHEME: "${PUSHER_SCHEME:-http}"
      PUSHER_APP_ID: "${PUSHER_APP_ID:-coolify}"
      PUSHER_APP_KEY: "${PUSHER_APP_KEY:-coolify}"
      PUSHER_APP_SECRET: "${PUSHER_APP_SECRET:-coolify}"
    volumes:
      - .:/var/www/html/:cached
  postgres:
    pull_policy: always
    ports:
      - "${FORWARD_DB_PORT:-5432}:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${DB_USERNAME:-coolify}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-password}"
      POSTGRES_DB: "${DB_DATABASE:-coolify}"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - /data/coolify/_volumes/database/:/var/lib/postgresql/data
      # - coolify-pg-data-dev:/var/lib/postgresql/data
  redis:
    pull_policy: always
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    env_file:
      - .env
    volumes:
      - /data/coolify/_volumes/redis/:/data
      # - coolify-redis-data-dev:/data
  soketi:
    env_file:
      - .env
    ports:
      - "${FORWARD_SOKETI_PORT:-6001}:6001"
    environment:
      SOKETI_DEBUG: "false"
      SOKETI_DEFAULT_APP_ID: "${PUSHER_APP_ID:-coolify}"
      SOKETI_DEFAULT_APP_KEY: "${PUSHER_APP_KEY:-coolify}"
      SOKETI_DEFAULT_APP_SECRET: "${PUSHER_APP_SECRET:-coolify}"
  vite:
    image: node:20
    pull_policy: always
    working_dir: /var/www/html
    # environment:
    # VITE_PUSHER_APP_KEY: "${PUSHER_APP_KEY:-coolify}"
    ports:
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    volumes:
      - .:/var/www/html:cached
    command: sh -c "npm install && npm run dev"
    networks:
      - coolify
  testing-host:
    image: "ghcr.io/coollabsio/coolify-testing-host:latest"
    pull_policy: always
    init: true
    container_name: coolify-testing-host
    volumes:
      - /:/host
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/coolify/:/data/coolify
    networks:
      - coolify
  mailpit:
    image: "axllent/mailpit:latest"
    pull_policy: always
    container_name: coolify-mail
    ports:
      - "${FORWARD_MAILPIT_PORT:-1025}:1025"
      - "${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025"
    networks:
      - coolify
  minio:
    image: minio/minio:latest
    pull_policy: always
    container_name: coolify-minio
    command: server /data --console-address ":9001"
    ports:
      - "${FORWARD_MINIO_PORT:-9000}:9000"
      - "${FORWARD_MINIO_PORT_CONSOLE:-9001}:9001"
    environment:
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY:-minioadmin}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY:-minioadmin}"
    volumes:
      - /data/coolify/_volumes/minio/:/data
      # - coolify-minio-data-dev:/data
    networks:
      - coolify

volumes:
  coolify-data-dev:
  coolify-pg-data-dev:
  coolify-redis-data-dev:
  coolify-minio-data-dev:


networks:
  coolify:
    name: coolify
    external: false

```
env file for reference:
```env
# Coolify Configuration
APP_ENV=local
# Comment out the line below to test the bug
APP_NAME="Coolify Development" 
APP_ID=development
APP_KEY=
APP_URL=http://localhost
APP_PORT=8000
APP_DEBUG=true
MUX_ENABLED=false

# Enable Laravel Telescope for debugging
TELESCOPE_ENABLED=false

# Selenium Driver URL for Dusk
DUSK_DRIVER_URL=http://selenium:4444

# PostgreSQL Database Configuration
DB_DATABASE=coolify
DB_USERNAME=coolify
DB_PASSWORD=password
DB_HOST=host.docker.internal
DB_PORT=5432

#Set custom ray port
RAY_PORT=9002

# Special Keys for Andras
# For cache purging
BUNNY_API_KEY=
# For asset uploads
BUNNY_STORAGE_API_KEY=

```
